# Generated by Django 3.2.4 on 2021-07-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('attend_no', models.CharField(db_column='ATTEND_NO', max_length=20, primary_key=True, serialize=False)),
                ('comp_no', models.CharField(db_column='COMP_NO', max_length=20)),
                ('rest_no', models.CharField(blank=True, db_column='REST_NO', max_length=20, null=True)),
                ('overtime_no', models.CharField(blank=True, db_column='OVERTIME_NO', max_length=20, null=True)),
                ('salary_no', models.CharField(db_column='SALARY_NO', max_length=20)),
                ('shift_no', models.CharField(db_column='SHIFT_NO', max_length=20)),
                ('punch_in', models.DateTimeField(blank=True, db_column='PUNCH_IN', null=True)),
                ('in_position', models.CharField(blank=True, db_column='IN_POSITION', max_length=50, null=True)),
                ('punch_out', models.DateTimeField(blank=True, db_column='PUNCH_OUT', null=True)),
                ('out_position', models.CharField(blank=True, db_column='OUT_POSITION', max_length=50, null=True)),
                ('attend_date', models.DateField(blank=True, db_column='ATTEND_DATE', null=True)),
            ],
            options={
                'db_table': 'ATTENDANCE_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('comp_no', models.CharField(db_column='COMP_NO', max_length=20, primary_key=True, serialize=False)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('punch_no', models.CharField(blank=True, db_column='PUNCH_NO', max_length=20, null=True)),
                ('shift_no', models.CharField(db_column='SHIFT_NO', max_length=20)),
                ('comp_name', models.CharField(db_column='COMP_NAME', max_length=50)),
            ],
            options={
                'db_table': 'COMPANY_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftsTable',
            fields=[
                ('shift_no', models.CharField(db_column='SHIFT_NO', max_length=20, primary_key=True, serialize=False)),
                ('group_no', models.CharField(db_column='GROUP_NO', max_length=20)),
                ('date', models.DateField(db_column='DATE')),
                ('shifts', models.IntegerField(db_column='SHIFTS')),
                ('punch_in', models.DateTimeField(blank=True, db_column='PUNCH_IN', null=True)),
                ('punch_out', models.DateTimeField(blank=True, db_column='PUNCH_OUT', null=True)),
            ],
            options={
                'db_table': 'SHIFTS_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzEmpTable',
            fields=[
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=50, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_column='EMP_NAME', max_length=30)),
                ('dep_no', models.CharField(db_column='DEP_NO', max_length=20)),
                ('user_no', models.CharField(db_column='USER_NO', max_length=20)),
                ('user_pwd', models.CharField(db_column='USER_PWD', max_length=20)),
                ('line_id', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'zz_EMP_TABLE',
                'managed': False,
            },
        ),
    ]
