# Generated by Django 3.2.4 on 2021-07-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestTable',
            fields=[
                ('rest_id', models.CharField(db_column='REST_ID', max_length=11)),
                ('rest_no', models.CharField(db_column='REST_NO', max_length=20, primary_key=True, serialize=False)),
                ('attend_no', models.CharField(db_column='ATTEND_NO', max_length=20)),
                ('rest_type', models.IntegerField(db_column='REST_TYPE')),
                ('app_date', models.DateField(db_column='APP_DATE')),
                ('rest_date', models.DateField(db_column='REST_DATE')),
                ('rest_reason', models.TextField(db_column='REST_REASON')),
            ],
            options={
                'db_table': 'REST_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestType',
            fields=[
                ('rest_type_id', models.CharField(db_column='REST_TYPE_ID', max_length=11)),
                ('rest_type_no', models.IntegerField(db_column='REST_TYPE_NO', primary_key=True, serialize=False)),
                ('rest_no', models.CharField(db_column='REST_NO', max_length=20)),
                ('type_name', models.CharField(db_column='TYPE_NAME', max_length=20)),
            ],
            options={
                'db_table': 'REST_TYPE',
                'managed': False,
            },
        ),
    ]
