# Generated by Django 3.2.5 on 2021-07-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0002_resttable_resttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpTable',
            fields=[
                ('emp_id', models.CharField(db_column='EMP_ID', max_length=11)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=50, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_column='EMP_NAME', max_length=30)),
                ('comp_no', models.CharField(db_column='COMP_NO', max_length=20)),
                ('dep_no', models.CharField(db_column='DEP_NO', max_length=20)),
                ('work_postition', models.CharField(db_column='WORK_POSTITION', max_length=20)),
                ('user_no', models.CharField(db_column='USER_NO', max_length=20)),
                ('user_pwd', models.CharField(db_column='USER_PWD', max_length=20)),
                ('line_id', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('group_no', models.CharField(blank=True, db_column='GROUP_NO', max_length=20, null=True)),
                ('group_leader', models.IntegerField(blank=True, db_column='GROUP_leader', null=True)),
                ('working', models.IntegerField(db_column='WORKING')),
            ],
            options={
                'db_table': 'EMP_TABLE',
                'managed': False,
            },
        ),
    ]
