# Generated by Django 3.2.4 on 2021-07-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('attend_id', models.CharField(db_column='ATTEND_ID', max_length=11)),
                ('attend_no', models.CharField(db_column='ATTEND_NO', max_length=20, primary_key=True, serialize=False)),
                ('comp_no', models.CharField(db_column='COMP_NO', max_length=20)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('attend_date', models.DateField(blank=True, db_column='ATTEND_DATE', null=True)),
                ('salary_no', models.CharField(db_column='SALARY_NO', max_length=20)),
                ('shift_no', models.CharField(db_column='SHIFT_NO', max_length=20)),
                ('rest_no', models.CharField(blank=True, db_column='REST_NO', max_length=20, null=True)),
                ('punch_in', models.DateTimeField(blank=True, db_column='PUNCH_IN', null=True)),
                ('in_position', models.CharField(blank=True, db_column='IN_POSITION', max_length=50, null=True)),
                ('punch_out', models.DateTimeField(blank=True, db_column='PUNCH_OUT', null=True)),
                ('out_position', models.CharField(blank=True, db_column='OUT_POSITION', max_length=50, null=True)),
                ('overtime_no', models.CharField(blank=True, db_column='OVERTIME_NO', max_length=20, null=True)),
            ],
            options={
                'db_table': 'ATTENDANCE_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('comp_id', models.CharField(db_column='COMP_ID', max_length=11)),
                ('comp_no', models.CharField(db_column='COMP_NO', max_length=20, primary_key=True, serialize=False)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('comp_name', models.CharField(db_column='COMP_NAME', max_length=50)),
            ],
            options={
                'db_table': 'COMPANY_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompTimeTable',
            fields=[
                ('comp_time_id', models.CharField(db_column='COMP_TIME_ID', max_length=11)),
                ('comp_time_no', models.CharField(db_column='COMP_TIME_NO', max_length=20, primary_key=True, serialize=False)),
                ('overtime_no', models.CharField(db_column='OVERTIME_NO', max_length=20)),
                ('total', models.IntegerField(db_column='TOTAL')),
            ],
            options={
                'db_table': 'COMP_TIME_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepTable',
            fields=[
                ('dep_no', models.IntegerField(db_column='DEP_NO', primary_key=True, serialize=False)),
                ('dep_name', models.CharField(db_column='DEP_NAME', max_length=20)),
            ],
            options={
                'db_table': 'DEP_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailsList',
            fields=[
                ('details_id', models.CharField(db_column='DETAILS_ID', max_length=11)),
                ('details_list', models.CharField(db_column='DETAILS_LIST', max_length=20, primary_key=True, serialize=False)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('salary_no', models.CharField(db_column='SALARY_NO', max_length=20)),
                ('salary', models.IntegerField(db_column='SALARY')),
                ('overtime_pay', models.IntegerField(db_column='OVERTIME_PAY')),
            ],
            options={
                'db_table': 'DETAILS_LIST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpTable',
            fields=[
                ('emp_id', models.CharField(db_column='EMP_ID', max_length=11)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=50, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_column='EMP_NAME', max_length=30)),
                ('comp_no', models.CharField(db_column='COMP_NO', max_length=20)),
                ('dep_no', models.CharField(db_column='DEP_NO', max_length=20)),
                ('work_postition', models.CharField(db_column='WORK_POSTITION', max_length=20)),
                ('user_no', models.CharField(db_column='USER_NO', max_length=20)),
                ('user_pwd', models.CharField(db_column='USER_PWD', max_length=20)),
            ],
            options={
                'db_table': 'EMP_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('group_no', models.CharField(db_column='GROUP_NO', max_length=20, primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='GROUP_NAME', max_length=50)),
            ],
            options={
                'db_table': 'GROUP_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimePay',
            fields=[
                ('overtime_pay_id', models.CharField(db_column='OVERTIME_PAY_ID', max_length=11)),
                ('overtime_pay_no', models.CharField(db_column='OVERTIME_PAY_NO', max_length=20, primary_key=True, serialize=False)),
                ('salary_no', models.CharField(db_column='SALARY_NO', max_length=20)),
                ('overtime_no', models.CharField(db_column='OVERTIME_NO', max_length=20)),
                ('overtime_pay', models.IntegerField(db_column='OVERTIME_PAY')),
            ],
            options={
                'db_table': 'OVERTIME_PAY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimeType',
            fields=[
                ('overtime_type_id', models.CharField(db_column='OVERTIME_TYPE_ID', max_length=11)),
                ('overtime_type', models.IntegerField(db_column='OVERTIME_TYPE', primary_key=True, serialize=False)),
                ('overtime_name', models.CharField(db_column='OVERTIME_NAME', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'OVERTIME_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PunchTable',
            fields=[
                ('punch_id', models.IntegerField(db_column='PUNCH_ID')),
                ('punch_no', models.CharField(db_column='PUNCH_NO', max_length=20, primary_key=True, serialize=False)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('punch_record', models.IntegerField(db_column='PUNCH_RECORD')),
                ('punch_date', models.DateTimeField(db_column='PUNCH_DATE')),
                ('punch_name', models.CharField(db_column='PUNCH_NAME', max_length=20)),
                ('punch_reason', models.TextField(db_column='PUNCH_REASON')),
            ],
            options={
                'db_table': 'PUNCH_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestTable',
            fields=[
                ('rest_id', models.CharField(db_column='REST_ID', max_length=11)),
                ('rest_no', models.CharField(db_column='REST_NO', max_length=20, primary_key=True, serialize=False)),
                ('attend_no', models.CharField(db_column='ATTEND_NO', max_length=20)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('rest_type', models.IntegerField(db_column='REST_TYPE')),
                ('app_date', models.DateField(db_column='APP_DATE')),
                ('rest_date', models.DateField(db_column='REST_DATE')),
                ('rest_reason', models.TextField(db_column='REST_REASON')),
            ],
            options={
                'db_table': 'REST_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestType',
            fields=[
                ('rest_type_id', models.CharField(db_column='REST_TYPE_ID', max_length=11)),
                ('rest_type_no', models.IntegerField(db_column='REST_TYPE_NO', primary_key=True, serialize=False)),
                ('rest_no', models.CharField(db_column='REST_NO', max_length=20)),
                ('type_name', models.CharField(db_column='TYPE_NAME', max_length=20)),
            ],
            options={
                'db_table': 'REST_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryTable',
            fields=[
                ('salary_id', models.CharField(db_column='SALARY_ID', max_length=11)),
                ('salary_no', models.CharField(db_column='SALARY_NO', max_length=20, primary_key=True, serialize=False)),
                ('attend_no', models.CharField(db_column='ATTEND_NO', max_length=20)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('details_list', models.CharField(db_column='DETAILS_LIST', max_length=20)),
                ('overtime_pay_no', models.CharField(db_column='OVERTIME_PAY_NO', max_length=20)),
                ('salary', models.IntegerField(db_column='SALARY')),
            ],
            options={
                'db_table': 'SALARY_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftsTable',
            fields=[
                ('shift_no', models.CharField(db_column='SHIFT_NO', max_length=20, primary_key=True, serialize=False)),
                ('attend_no', models.CharField(blank=True, db_column='ATTEND_NO', max_length=20, null=True)),
                ('group_no', models.CharField(db_column='GROUP_NO', max_length=20)),
                ('emp_no', models.CharField(db_column='EMP_NO', max_length=20)),
                ('date', models.DateField(db_column='DATE')),
                ('punch_in', models.DateTimeField(auto_now=True, db_column='PUNCH_IN', null=True)),
                ('punch_out', models.DateTimeField(auto_now=True, db_column='PUNCH_OUT', null=True)),
            ],
            options={
                'db_table': 'SHIFTS_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOvertime',
            fields=[
                ('overtime_id', models.CharField(db_column='OVERTIME_ID', max_length=11)),
                ('overtime_no', models.CharField(db_column='OVERTIME_NO', max_length=20, primary_key=True, serialize=False)),
                ('attend_no', models.CharField(db_column='ATTEND_NO', max_length=20)),
                ('overtime_pay_no', models.CharField(db_column='OVERTIME_PAY_NO', max_length=20)),
                ('overtime_date', models.DateField(db_column='OVERTIME_DATE')),
                ('punch_in', models.DateTimeField(blank=True, db_column='PUNCH_IN', null=True)),
                ('punch_out', models.DateTimeField(blank=True, db_column='PUNCH_OUT', null=True)),
                ('overtime_hours', models.IntegerField(db_column='OVERTIME_HOURS')),
                ('overtime_check', models.IntegerField(db_column='OVERTIME_CHECK')),
                ('comp_time_no', models.CharField(blank=True, db_column='COMP_TIME_NO', max_length=20, null=True)),
                ('hours_change', models.IntegerField(blank=True, db_column='HOURS_CHANGE', null=True)),
                ('disaster', models.IntegerField(blank=True, db_column='DISASTER', null=True)),
                ('no_rest', models.IntegerField(blank=True, db_column='NO_REST', null=True)),
            ],
            options={
                'db_table': 'WORK_OVERTIME',
                'managed': False,
            },
        ),
    ]
