"""
Django settings for mylinebot project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ptt0oq10wusdvstr5yk%o80p59kh@z)xxs^)yhgh3=g!hw*x(9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允許的網域名稱
ALLOWED_HOSTS = [
    # '4fbeaa5e4d28.ngrok.io'  # 允許的網域名稱
    #'clockinlinebot.herokuapp.com'
     '210.71.231.174',
     'hrcslinebot.justright.com.tw',
     'cgpt-hrcs-linebot.azurewebsites.net'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# 新建立的Django應用程式(APP)
    'clockInlinebot.apps.ClockinlinebotConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mylinebot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path(BASE_DIR, 'clockInlinebot/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mylinebot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#資料庫配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hrcs',
        'USER': 'hrcs',
        'PASSWORD': 'M*Jyg3@H!sV*',
        'HOST': 'cgpt-mysql.mysql.database.azure.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {'ca': '',},
        },
    },
    'HRCS_test':{   #配置第二個資料庫節點名稱
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hrcs_fh',
        'USER': 'hrcs',
        'PASSWORD': 'M*Jyg3@H!sV*',
        'HOST': 'cgpt-mysql.mysql.database.azure.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {'ca': '',},
        },
    }
}

DATABASE_ROUTERS = ['mylinebot.database_router.HRCS_test_Router']



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'clockInlinebot/static/'
STATICFILES_DIRS = [
    BASE_DIR / "clockInlinebot/static",
]

STATIC_ROOT = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LINE Developers上所取得的兩個憑證設定，來與LINE頻道(Channel)進行連結
LINE_CHANNEL_ACCESS_TOKEN = 'WHpy0NgirSDmNdA/UzjhKRYVuKU3yvR95KcfKvb8UgE7oPvW/Q8Hnq28aqU04YU1Ks/yH+6SgFiFYs7zoo1ON5GDIx8fFgpBhXEYbuQ4H1b3JaRxyW+k3vdMImfwFetrxv/FuItDbgWBmPvA19uYmAdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = '23302271bf3a8533351b692afa0a7976'
